apiVersion: v1
kind: Service
metadata:
  name: php-mysql
  labels:
    app: php
spec:
  ports:
    - port: 3306
  selector:
    app: php
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-mysql
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
        tier: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: $3cr3t#p@$Sw0rD
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: php-frontend
  labels:
    app: php-frontend
spec:
  ports:
    - port: 80
  selector:
    app: php-frontend
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-frontend
  labels:
    app: php-frontend
spec:
  selector:
    matchLabels:
      app: php-frontend
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-frontend
        tier: frontend
    spec:
      containers:
      - image: php-mysql:vault
        name: php-frontend
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: php-frontend
        volumeMounts:
        - name: php-frontend-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: php-frontend-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim